<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cor extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Cores_model');
    } 

    /*
     * Listing of cores
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('cor/index?');
        $config['total_rows'] = $this->Cores_model->get_all_cores_count();
        $this->pagination->initialize($config);

        $data['cores'] = $this->Cores_model->get_all_cores($params);
        
        $data['_view'] = 'cor/index';
        $this->load->view('common/header');
        $this->load->view('common/menu');
        $this->load->view('layouts/main',$data);
        $this->load->view('common/footer');
    }

    /*
     * Adding a new cor
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('cor','Cor','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'cor' => $this->input->post('cor'),
            );
            
            $cor_id = $this->Cores_model->add_cor($params);
            redirect('cor/index');
        }
        else
        {            
            $data['_view'] = 'cor/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a cor
     */
    function edit($id)
    {   
        // check if the cor exists before trying to edit it
        $data['cor'] = $this->Cores_model->get_cor($id);
        
        if(isset($data['cor']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('cor','Cor','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'cor' => $this->input->post('cor'),
                );

                $this->Cores_model->update_cor($id,$params);            
                redirect('cor/index');
            }
            else
            {
                $data['_view'] = 'cor/edit';
                $this->load->view('common/header');
                $this->load->view('common/menu');
                $this->load->view('layouts/main',$data);
                $this->load->view('common/footer');
            }
        }
        else
            show_error('The cor you are trying to edit does not exist.');
    } 

    /*
     * Deleting cor
     */
    function remove($id)
    {
        $cor = $this->Cores_model->get_cor($id);

        // check if the cor exists before trying to delete it
        if(isset($cor['id']))
        {
            $this->Cores_model->delete_cor($id);
            redirect('cor/index');
        }
        else
            show_error('The cor you are trying to delete does not exist.');
    }
    
}
