<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Modelo extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Modelo_model');
    } 

    /*
     * Listing of modelos
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('modelo/index?');
        $config['total_rows'] = $this->Modelo_model->get_all_modelos_count();
        $this->pagination->initialize($config);

        $data['modelos'] = $this->Modelo_model->get_all_modelos($params);
        
        $data['_view'] = 'modelo/index';
        $this->load->view('common/header');
        $this->load->view('common/menu');
        $this->load->view('layouts/main',$data);
        $this->load->view('common/footer');
    }

    /*
     * Adding a new modelo
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('modelo','Modelo','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'modelo' => $this->input->post('modelo'),
				'descricao' => $this->input->post('descricao'),
            );
            
            $modelo_id = $this->Modelo_model->add_modelo($params);
            redirect('modelo/index');
        }
        else
        {            
            $data['_view'] = 'modelo/add';
            $this->load->view('common/header');
            $this->load->view('common/menu');
            $this->load->view('layouts/main',$data);
            $this->load->view('common/footer');
        }
    }  

    /*
     * Editing a modelo
     */
    function edit($id)
    {   
        // check if the modelo exists before trying to edit it
        $data['modelo'] = $this->Modelo_model->get_modelo($id);
        
        if(isset($data['modelo']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('modelo','Modelo','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'modelo' => $this->input->post('modelo'),
					'descricao' => $this->input->post('descricao'),
                );

                $this->Modelo_model->update_modelo($id,$params);            
                redirect('modelo/index');
            }
            else
            {
                $data['_view'] = 'modelo/edit';
                $this->load->view('common/header');
                $this->load->view('common/menu');
                $this->load->view('layouts/main',$data);
                $this->load->view('common/footer');
            }
        }
        else
            show_error('The modelo you are trying to edit does not exist.');
    } 

    /*
     * Deleting modelo
     */
    function remove($id)
    {
        $modelo = $this->Modelo_model->get_modelo($id);

        // check if the modelo exists before trying to delete it
        if(isset($modelo['id']))
        {
            $this->Modelo_model->delete_modelo($id);
            redirect('modelo/index');
        }
        else
            show_error('The modelo you are trying to delete does not exist.');
    }
    
}
