<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tamanho extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tamanho_model');
    } 

    /*
     * Listing of tamanhos
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tamanho/index?');
        $config['total_rows'] = $this->Tamanho_model->get_all_tamanhos_count();
        $this->pagination->initialize($config);

        $data['tamanhos'] = $this->Tamanho_model->get_all_tamanhos($params);
        
        $data['_view'] = 'tamanho/index';
        $this->load->view('common/header');
        $this->load->view('common/menu');
        $this->load->view('layouts/main',$data);
        $this->load->view('common/footer');
    }

    /*
     * Adding a new tamanho
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('tamanho','Tamanho','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'tamanho' => $this->input->post('tamanho'),
            );
            
            $tamanho_id = $this->Tamanho_model->add_tamanho($params);
            redirect('tamanho/index');
        }
        else
        {            
            $data['_view'] = 'tamanho/add';
            $this->load->view('common/header');
            $this->load->view('common/menu');
            $this->load->view('layouts/main',$data);
            $this->load->view('common/footer');
        }
    }  

    /*
     * Editing a tamanho
     */
    function edit($id)
    {   
        // check if the tamanho exists before trying to edit it
        $data['tamanho'] = $this->Tamanho_model->get_tamanho($id);
        
        if(isset($data['tamanho']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('tamanho','Tamanho','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'tamanho' => $this->input->post('tamanho'),
                );

                $this->Tamanho_model->update_tamanho($id,$params);            
                redirect('tamanho/index');
            }
            else
            {
                $data['_view'] = 'tamanho/edit';
                $this->load->view('common/header');
                $this->load->view('common/menu');
                $this->load->view('layouts/main',$data);
                $this->load->view('common/footer');
            }
        }
        else
            show_error('The tamanho you are trying to edit does not exist.');
    } 

    /*
     * Deleting tamanho
     */
    function remove($id)
    {
        $tamanho = $this->Tamanho_model->get_tamanho($id);

        // check if the tamanho exists before trying to delete it
        if(isset($tamanho['id']))
        {
            $this->Tamanho_model->delete_tamanho($id);
            redirect('tamanho/index');
        }
        else
            show_error('The tamanho you are trying to delete does not exist.');
    }
    
}
