<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Cores_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get cor by id
     */
    function get_cor($id)
    {
        return $this->db->get_where('cores',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all cores count
     */
    function get_all_cores_count()
    {
        $this->db->from('cores');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all cores
     */
    function get_all_cores($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('cores')->result_array();
    }
        
    /*
     * function to add new cor
     */
    function add_cor($params)
    {
        $this->db->insert('cores',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update cor
     */
    function update_cor($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('cores',$params);
    }
    
    /*
     * function to delete cor
     */
    function delete_cor($id)
    {
        return $this->db->delete('cores',array('id'=>$id));
    }
}
