<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Modelo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get modelo by id
     */
    function get_modelo($id)
    {
        return $this->db->get_where('modelos',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all modelos count
     */
    function get_all_modelos_count()
    {
        $this->db->from('modelos');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all modelos
     */
    function get_all_modelos($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('modelos')->result_array();
    }
        
    /*
     * function to add new modelo
     */
    function add_modelo($params)
    {
        $this->db->insert('modelos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update modelo
     */
    function update_modelo($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('modelos',$params);
    }
    
    /*
     * function to delete modelo
     */
    function delete_modelo($id)
    {
        return $this->db->delete('modelos',array('id'=>$id));
    }
}
