<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tamanho_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tamanho by id
     */
    function get_tamanho($id)
    {
        return $this->db->get_where('tamanhos',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all tamanhos count
     */
    function get_all_tamanhos_count()
    {
        $this->db->from('tamanhos');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tamanhos
     */
    function get_all_tamanhos($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tamanhos')->result_array();
    }
        
    /*
     * function to add new tamanho
     */
    function add_tamanho($params)
    {
        $this->db->insert('tamanhos',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tamanho
     */
    function update_tamanho($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tamanhos',$params);
    }
    
    /*
     * function to delete tamanho
     */
    function delete_tamanho($id)
    {
        return $this->db->delete('tamanhos',array('id'=>$id));
    }
}
